--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JeroGamingYT/NoAdvertisings
build-by-default: true
branches:
- pm4
- pm5
projects:
  NoAdvertisings:
    path: ""
    icon: icon.png
...
